app = "visual-key-api"
primary_region = "cdg"

kill_signal = "SIGTERM"
kill_timeout = 120

[deploy]
  strategy = "canary"

[env]
  HTTP_PORT = "80"
  ENVIRONMENT = "prod"
  BEHIND_PROXY = "true"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 2048
    hard_limit = 4096
